---
- hosts: localhost
  connection: local
  gather_facts: false
  become: false
  tasks:
    - name: Check if jq is installed
      command: command -v jq
      register: jq_installed
      failed_when: false
      changed_when: false

    - name: Install jq
      apt:
        name: jq
        state: present
      when: jq_installed.rc != 0
