---
- hosts: localhost
  connection: local
  gather_facts: false
  tasks:

    - name: Check if Ansible is installed
      command: ansible-config --version
      register: ansible_check
      changed_when: false
      ignore_errors: true

    - name: Install Ansible
      pip:
        name: ansible
        state: latest
      when: ansible_check.failed

    - name: Check Ansible version
      command: ansible-config --version
      register: version
      changed_when: false

    - name: Print Ansible version
      debug: var=version.stdout_lines

    - name: Create Ansible configuration file
      blockinfile:
        path: "/home/devnet/workshop/DEVWKS-1423/ansible.cfg"
        create: true
        block: |
          [defaults]
          gathering = explicit
          host_key_checking = True
          timeout = 30
          deprecation_warnings = False
          retry_files_enabled = False
          DEFAULT_LOCAL_TMP = ./ansible_tmp
          transport = paramiko
          look_for_keys = False

    - name: Verify Ansible configuration file
      command: cat /home/devnet/workshop/DEVWKS-1423/ansible.cfg
      register: config
      changed_when: false

    - debug: var=config.stdout_lines
...
